#server.tomcat.max-threads=600
#server.tomcat.max-connections=10000
#server.tomcat.min-spare-threads=600
#200 1900  400 3800  600 4600  800 4500
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3312/test
#spring.datasource.username=root
#spring.datasource.password=123456
druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        url: jdbc:mysql://localhost:3310/test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        initial-size: 100
        min-idle: 100
        max-active: 100
#        test-on-borrow: true
        maxWait: 2000
    slave:
        url: jdbc:mysql://localhost:3312/test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
        username: cx
        password: 123456
        initial-size: 100
        min-idle: 100
        max-active: 100
#        test-on-borrow: true
        maxWait: 2000
